version: '3.8'

services:

  tf-cube:
    image: tensorflow/tensorflow:latest-gpu-jupyter
    container_name: tf-cube
    ports:
      - "18888:8888"
    deploy:
      resources:
        reservations:
          devices:
          - driver: "nvidia"
            device_ids: ["0"]
            capabilities: [gpu]
    volumes:
      - ./Reinforcement-Learning-Algorithms-with-Python:/tf/Reinforcement-Learning-Algorithms-with-Python
